# Generated by Django 5.2.17 on 2026-10-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('READ_ONLY', 'Read-Only')], default='READ_ONLY', max_length=20),
        ),
    ]
