# Generated by Django 5.2.17 on 2026-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW_TRANSACTION', 'View Transaction'), ('EXPORT_TRANSACTION', 'Export Transaction'), ('UPDATE_TRANSACTION', 'Update Transaction'), ('UPDATE_USER', 'Update User'), ('DELETE_CARD', 'Delete Card'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
