# Generated by Django 5.2.17 on 2026-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW_TRANSACTION', 'View Transaction'), ('EXPORT_TRANSACTION', 'Export Transaction'), ('UPDATE_TRANSACTION', 'Update Transaction'), ('UPDATE_USER', 'Update User'), ('DELETE_CARD', 'Delete Card'), ('BLOCK_CARD', 'Block Card'), ('UNBLOCK_CARD', 'Unblock Card'), ('UPDATE_CREDIT_LIMIT', 'Update Credit Limit'), ('FRAUD_ALERT', 'Fraud Alert'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
