# Generated by Django 5.2.17 on 2026-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fraud_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
