# Generated by Django 5.2.17 on 2026-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_fraud_reason_transaction_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
