# Generated by Django 5.2.17 on 2026-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=10),
            preserve_default=False,
        ),
    ]
